// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto_file.proto

//это название озночает что в этом файле хранятся все нужные сервисы и сообщения

package protoYLMS

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Arg1          float32                `protobuf:"fixed32,2,opt,name=Arg1,proto3" json:"Arg1,omitempty"`
	Arg2          float32                `protobuf:"fixed32,3,opt,name=Arg2,proto3" json:"Arg2,omitempty"`
	Operation     string                 `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	OperationTime string                 `protobuf:"bytes,5,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskRequest) GetArg1() float32 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *TaskRequest) GetArg2() float32 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *TaskRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *TaskRequest) GetOperationTime() string {
	if x != nil {
		return x.OperationTime
	}
	return ""
}

type ListTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*TaskRequest         `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskRequest) Reset() {
	*x = ListTaskRequest{}
	mi := &file_proto_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskRequest) ProtoMessage() {}

func (x *ListTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskRequest.ProtoReflect.Descriptor instead.
func (*ListTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{1}
}

func (x *ListTaskRequest) GetList() []*TaskRequest {
	if x != nil {
		return x.List
	}
	return nil
}

type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float32                `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_proto_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{2}
}

func (x *ResultRequest) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ResultRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ProcessedExpressionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Result        float32                `protobuf:"fixed32,3,opt,name=Result,proto3" json:"Result,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessedExpressionRequest) Reset() {
	*x = ProcessedExpressionRequest{}
	mi := &file_proto_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedExpressionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedExpressionRequest) ProtoMessage() {}

func (x *ProcessedExpressionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedExpressionRequest.ProtoReflect.Descriptor instead.
func (*ProcessedExpressionRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessedExpressionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProcessedExpressionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessedExpressionRequest) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ProcessedExpressionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListProcesedExpressionRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	List          []*ProcessedExpressionRequest `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcesedExpressionRequest) Reset() {
	*x = ListProcesedExpressionRequest{}
	mi := &file_proto_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcesedExpressionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcesedExpressionRequest) ProtoMessage() {}

func (x *ListProcesedExpressionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcesedExpressionRequest.ProtoReflect.Descriptor instead.
func (*ListProcesedExpressionRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{4}
}

func (x *ListProcesedExpressionRequest) GetList() []*ProcessedExpressionRequest {
	if x != nil {
		return x.List
	}
	return nil
}

var File_proto_file_proto protoreflect.FileDescriptor

const file_proto_file_proto_rawDesc = "" +
	"\n" +
	"\x10proto_file.proto\x12\x06global\x1a\x1bgoogle/protobuf/empty.proto\"\x8a\x01\n" +
	"\vTaskRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x12\n" +
	"\x04Arg1\x18\x02 \x01(\x02R\x04Arg1\x12\x12\n" +
	"\x04Arg2\x18\x03 \x01(\x02R\x04Arg2\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\x12%\n" +
	"\x0eoperation_time\x18\x05 \x01(\tR\roperationTime\":\n" +
	"\x0fListTaskRequest\x12'\n" +
	"\x04List\x18\x01 \x03(\v2\x13.global.TaskRequestR\x04List\"@\n" +
	"\rResultRequest\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x02R\x06result\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"u\n" +
	"\x1aProcessedExpressionRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\tR\x06Status\x12\x16\n" +
	"\x06Result\x18\x03 \x01(\x02R\x06Result\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"W\n" +
	"\x1dListProcesedExpressionRequest\x126\n" +
	"\x04List\x18\x01 \x03(\v2\".global.ProcessedExpressionRequestR\x04List2Q\n" +
	"\x0fInternalService\x12>\n" +
	"\tPushTasks\x12\x17.global.ListTaskRequest\x1a\x16.google.protobuf.Empty\"\x002\x82\x01\n" +
	"\vTaskService\x128\n" +
	"\aGetTask\x12\x16.google.protobuf.Empty\x1a\x13.global.TaskRequest\"\x00\x129\n" +
	"\bPushTask\x12\x13.global.TaskRequest\x1a\x16.google.protobuf.Empty\"\x002\xcb\x01\n" +
	"\x1bProcessedExpressionsService\x12M\n" +
	"\x1aPushNewProcessedExpression\x12\x15.global.ResultRequest\x1a\x16.google.protobuf.Empty\"\x00\x12]\n" +
	"\x1aGetAllProcessedExpressions\x12\x16.google.protobuf.Empty\x1a%.global.ListProcesedExpressionRequest\"\x00B\x1dZ\x1bgithub.com/bust6k/protoYLMSb\x06proto3"

var (
	file_proto_file_proto_rawDescOnce sync.Once
	file_proto_file_proto_rawDescData []byte
)

func file_proto_file_proto_rawDescGZIP() []byte {
	file_proto_file_proto_rawDescOnce.Do(func() {
		file_proto_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_file_proto_rawDesc), len(file_proto_file_proto_rawDesc)))
	})
	return file_proto_file_proto_rawDescData
}

var file_proto_file_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_file_proto_goTypes = []any{
	(*TaskRequest)(nil),                   // 0: global.TaskRequest
	(*ListTaskRequest)(nil),               // 1: global.ListTaskRequest
	(*ResultRequest)(nil),                 // 2: global.ResultRequest
	(*ProcessedExpressionRequest)(nil),    // 3: global.ProcessedExpressionRequest
	(*ListProcesedExpressionRequest)(nil), // 4: global.ListProcesedExpressionRequest
	(*emptypb.Empty)(nil),                 // 5: google.protobuf.Empty
}
var file_proto_file_proto_depIdxs = []int32{
	0, // 0: global.ListTaskRequest.List:type_name -> global.TaskRequest
	3, // 1: global.ListProcesedExpressionRequest.List:type_name -> global.ProcessedExpressionRequest
	1, // 2: global.InternalService.PushTasks:input_type -> global.ListTaskRequest
	5, // 3: global.TaskService.GetTask:input_type -> google.protobuf.Empty
	0, // 4: global.TaskService.PushTask:input_type -> global.TaskRequest
	2, // 5: global.ProcessedExpressionsService.PushNewProcessedExpression:input_type -> global.ResultRequest
	5, // 6: global.ProcessedExpressionsService.GetAllProcessedExpressions:input_type -> google.protobuf.Empty
	5, // 7: global.InternalService.PushTasks:output_type -> google.protobuf.Empty
	0, // 8: global.TaskService.GetTask:output_type -> global.TaskRequest
	5, // 9: global.TaskService.PushTask:output_type -> google.protobuf.Empty
	5, // 10: global.ProcessedExpressionsService.PushNewProcessedExpression:output_type -> google.protobuf.Empty
	4, // 11: global.ProcessedExpressionsService.GetAllProcessedExpressions:output_type -> global.ListProcesedExpressionRequest
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_file_proto_init() }
func file_proto_file_proto_init() {
	if File_proto_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_file_proto_rawDesc), len(file_proto_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_file_proto_goTypes,
		DependencyIndexes: file_proto_file_proto_depIdxs,
		MessageInfos:      file_proto_file_proto_msgTypes,
	}.Build()
	File_proto_file_proto = out.File
	file_proto_file_proto_goTypes = nil
	file_proto_file_proto_depIdxs = nil
}
